language: c

before_install:
 - sudo apt-get update
 - sudo apt-get -y install linux-headers-generic

install:
 - make CURRENT=$(ls /lib/modules | head -1)
 - sudo make install

script:
 - echo "No tests yet"
